Feature/dropdown
TTG-Club/ttg-club-frontend pull request #143
Opened 2023-06-01 14:52 UTC by svifty7

2023-10-22 17:02 UTC, olegvolkov91 requested changes

2023-10-22 17:02 UTC, olegvolkov91 commented on src/shared/ui/kit/UiDropdown.vue
> +    focused.value ? 'arrow/up' : 'arrow/down'
чисто вкусовщина => `arrow/${focused.value ? 'up' : 'down'}`

2023-10-22 22:56 UTC, UrSenpaiii commented on src/shared/ui/kit/UiDropdown.vue
> +    modelValue: {
крутяк, не знал об этой штуке. Переделал на нее

2023-10-22 22:57 UTC, UrSenpaiii commented on src/shared/ui/kit/UiDropdown.vue
> +  import { xor } from 'lodash';
это idea всё сама там правила)

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +    }
лучше переделать на 
```typescript
defineProps<{
  label: string;
  trackBy: string;
  options: Array<T>;
  disabled?: boolean;
  isMultiple?: boolean;
  isSearchable?: boolean;
}>()
```

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  const dropdownHeader = ref<HTMLDivElement | null>(null);
вкусовщина, но так кода меньше)
```ts
const dropdownHeader = ref<HTMLDivElement>();
```

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  const filter = ref<string>('');
тут типизация уже излишняя

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  const selectedOptions = ref<Array<Object>>([]);
вместо `Object` нужно описать тип или использовать generic `T`

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +<script setup lang="ts">
можно добавить generic `generic="T extends Record<string, unknown>"`

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  const modelValue = defineModel();
типизируем из дженерика `T`

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  };
1. аналогично типизируем `Object`, в остальных местах тоже учесть нужно
2. `trackBy` лучше сделать строкой, и использовать как `option[props.trackBy]` (с `props.label` такая же фигня - учесть везде надо))

2023-11-16 18:22 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  });
однобуквенные переменные потом усложнят сильно понимание кода, нужно переписать на осмысленные, либо `value`))

2023-11-16 22:27 UTC, UrSenpaiii commented on src/shared/ui/kit/UiDropdown.vue
> +    }
А шо, так можно было, ДА?)

2023-11-16 22:30 UTC, UrSenpaiii commented on src/shared/ui/kit/UiDropdown.vue
> +  const filter = ref<string>('');
По поводу типизайций там еще нужно будет поглядеть

2023-11-16 22:36 UTC, UrSenpaiii commented on src/shared/ui/kit/UiDropdown.vue
> +  };
Вот тут проблемка, оно не просто так функция.
Что делать, если trackBy или option нужны свойства второго и более уровня?
К примеру ```race.name.rus```

2023-11-20 20:27 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  const filter = ref<string>('');
если ты указываешь строку как значение по умолчанию, то он автоматически присваивает тип)

2023-11-20 20:30 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +  };
первый способ для типизации лучше

2023-11-20 20:31 UTC, svifty7 commented on src/shared/ui/kit/UiDropdown.vue
> +    }
конечно)) мы все так новое делаем))

2024-03-13 20:48 UTC, svifty7 commented on src/pages/tools/ability-calc/ability-races/AbilityRaces.vue
> +        v-model="selectedChoiceDouble"
по всему МРу пересмотри, пожалуйста, зачем `v-model`, когда есть `@update:model-value`, и наоборот?
может стоит от чего-то отказаться? сразу скажу, что `v-model` через `computed(() => {get: () => {}, set: (v) => {}})` так себе затея, читать потом сложнее))

2024-03-13 20:48 UTC, svifty7 commented on src/pages/tools/encounters/EncountersView.vue
> +  const sendForm = throttle(async function () {
тут можно сделать стрелочную функцию вместо `async function ()` и после этого убрать коммент для отключения линтера)

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    headerLabel?: string | number;
Мне кажется, стоит убрать этот пропс. Вместо него надо создать компонент `<ui-form-item/>` с пропсом И слотом `label`

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    trackBy: string;
а эти два пропса переименовать в `label-key`, `value-key`

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    isGrouped?: boolean;
пропсы без `is` лучше будут смотреться, наверное, а последний можно переименовать в `grouping`

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    groupValues?: string;
эти пропсы для лучшего понимания стоит закончить на `Key`

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +  const input = ref<typeof UiInput | null>(null);
можно опустить оба `null` и проверять переменную на `undefined`

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +  const focused = ref<Boolean>(false);
тут можно или опустить излишнюю типизацацию, или сделать её примитивом `boolean` вместо конструктора)

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    }
слей себе последний дев и пройдись линтером)))

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +  const isSelectedClass = (option: T) =>
почему `Class`?

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    isEqual(modelValue.value, option);
может стоит проверять по `option[props.valueKey]`?

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    }
посмотри у vueuse композиции для отслеживания состояния фокуса, возможно это поможет сократить код и не придется поддерживать самим состояние фокуса?

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    get(modelValue.value, props.label),
если используешь данный хелпер, то думаю стоит по всему компоненту в похожих местах им пользоваться, а не только в 1-2 случаях)

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +  });
предлагаю вот такой вариант вместо переменных и `else`)
```typescript
const filteredOptions = computed<Array<T>>(() => {
  if (props.isGrouped) {
    return props.options.reduce(
      (res, el) => [
        ...res,
        { ...el[props.groupLabel], groupLabel: true },
        ...el[props.groupValues],
      ],
     [],
    );
  }
     
  return props.options.filter((el) => {
    const optionLabel = String(get(el, props.label)).toUpperCase();
    const currentFilter = String(filter.value).toUpperCase();

    return optionLabel.includes(currentFilter);
  });
});
```

2024-03-13 20:48 UTC, svifty7 commented on src/shared/ui/kit/UiMultiselect.vue
> +    modelValue.value = option;
тут стоит использовать `cloneDeep`

2024-03-13 22:19 UTC, UrSenpaiii commented on src/pages/admin/youtube/YoutubeView.vue
> -              :model-value="itemsPerPage.find((item) => item.value === size)"
При селекте опшина из списка он так или иначе триггерит `update:model-value` и передаёт туда выбранное значение, которое мы накидываем на `size`.
Ну как бы можно сделать прослойку в виде переменной по типу `selectedPageSize`, но зачем?
Т.е. там два варианта, мы передаем `model-value` и он просто обновляется сам или же ловим ивент `update:model-value` и делаем что-то более специфическое с выбранными данными

2024-03-13 22:21 UTC, UrSenpaiii commented on src/pages/character/classes/classes-detail/ClassDetail.vue
> +            v-model="currentSelectArchetype"
А поточнее?

2024-03-13 22:21 UTC, UrSenpaiii commented on src/pages/character/classes/classes-detail/ClassDetail.vue
> +  const getSelectedArchetype = () => {
да он какой-то нагроможденный, блин(

2024-03-13 22:54 UTC, UrSenpaiii commented on src/pages/tools/ability-calc/AbilityRandom.vue
> +        <template #option="{ name, key }">
Да я вообще думал, может реализовать вот эту синию точку внутри компонента, т.к. при мультивыборе можно как раз ей отмечать выбранный пул элементов. Как думаешь?

P.S дада, мультиселект не реализован, т.к еще нигде не использовался на сайте)

2024-03-13 22:58 UTC, UrSenpaiii commented on src/pages/tools/ability-calc/ability-races/AbilityRaces.vue
> -        :custom-label="({ name: { rus } }) => rus"
что именно? по функции?
Я как раз так изначально и сделал, мы по итогу решили сменить на текущий вариант. Ну и я не совсем понимаю, зачем

2024-03-13 23:00 UTC, UrSenpaiii commented on src/pages/tools/ability-calc/ability-races/AbilityRaces.vue
> +        v-model="selectedChoiceDouble"
Пока чуть выше тебе отписывал, как раз словил себя на этой же мысле 
> Т.е. там два варианта, мы передаем model-value и он просто обновляется сам или же ловим ивент update:model-value и делаем что-то более специфическое с выбранными данными
Следовательно сейчас упрощу, где можно

2024-03-13 23:06 UTC, UrSenpaiii commented on src/shared/ui/kit/UiMultiselect.vue
> +    headerLabel?: string | number;
Вообще изначально реализовал как и в прошлом селекте через `slot`, а вот `placeholder` сразу через `props`.
И вот пока писал, думал, делать ли `placeholder` тоже через `slot`, как было в прошлом или переводить `label` в `prop`, а может и то и другое сделать. Но так как за всё время `slot` был излишен - сделал через `prop`.

2024-03-13 23:15 UTC, UrSenpaiii commented on src/shared/ui/kit/UiMultiselect.vue
> +    isGrouped?: boolean;
Вообще это правило именования булевых переменных. А еще раньше чтобы вместо `<div is-searchable="true" />` можно было указать просто `<div is-searchable />` обязательно нужен был префикс is в названии.

2024-03-13 23:21 UTC, UrSenpaiii commented on src/shared/ui/kit/UiMultiselect.vue
> +  const isSelectedClass = (option: T) =>
Рудимент, просто изначально юзается для навешивания css класса

2024-03-13 23:27 UTC, UrSenpaiii commented on src/shared/ui/kit/UiMultiselect.vue
> +    isEqual(modelValue.value, option);
значения `option` нужно брать только через `get()`, так как `option[key]` не работает в случае, если свойтв больше, чем одно. `get()` делает deep search так сказать)

2024-03-13 23:51 UTC, UrSenpaiii commented on src/shared/ui/kit/UiMultiselect.vue
> +    get(modelValue.value, props.label),
Этот именно для реактивного рендера `SelectedOptions`. а так, `get()` используется немного с разными аргументами, да и сам по себе он вполне лаконичен

2024-03-13 23:59 UTC, UrSenpaiii commented on src/shared/ui/kit/UiMultiselect.vue
> +  });
Буквально у друзей в дс консультировался как лучше)

вот такой вот вариант был)
`
  const filteredOptions = computed(() =>
    props.isGrouped
      ? props.options.reduce(
          (res, el) => [
            ...res,
            { ...el[props.groupLabelKey], groupLabel: true },
            ...el[props.groupValuesKey],
          ],
          newOptions,
        )
      : props.options.filter((el) => {
          const optionLabel = String(get(el, props.labelKey)).toUpperCase();
          const currentFilter = String(filter.value).toUpperCase();

          return optionLabel.includes(currentFilter);
        }),
  );
`

А так я просто придерживаюсь одного `return`, мол одна точка выхода их кода, блаблабла)

2026-06-26 08:22 UTC, closed without merging