youtube editing page
TTG-Club/ttg-club-frontend pull request #164
Opened 2023-07-05 01:49 UTC by svifty7

2023-07-05 13:38 UTC, TroAlexis requested changes

2023-07-05 13:38 UTC, TroAlexis commented on src/common/services/HTTPService.ts
> +  );
может это в другой сервис вынести, HTTPService - это ведь дженерик сервис? выглядит как часть фичи или типа того

2023-07-05 13:38 UTC, TroAlexis commented on src/components/UI/kit/UiSwitch.vue
> +      </span>
дублирование обёртки

2023-07-05 13:38 UTC, TroAlexis commented on src/features/bookmarks/api/index.ts
> +    const http = useAxios();
а зачем нужно в каждом методе вызывать useAxios?

2023-07-05 13:38 UTC, TroAlexis commented on src/features/youtube/components/YoutubeAddVideo.vue
> +  const rules = reactive({
а здесь точно нужна reactive обёртка?

2023-07-05 13:38 UTC, TroAlexis commented on src/features/youtube/components/YoutubeEditVideo.vue
> +  };
было бы прикольно сделать композицию для абстракции такой логики, чтобы в каждом запросе не повторять конструкцию с isLoading
типа:
```ts
const {isLoading, withLoading} = useLoading();
withLoading(() => {
try {
  const result = await getData();
  // blabla
} catch {
  // blabla
}
});
```

2023-07-05 13:38 UTC, TroAlexis commented on src/features/youtube/components/YoutubePlayer.vue
>        h(
а чем в этом компоненте обусловлено использование рендер-функций?

2023-07-05 13:38 UTC, TroAlexis commented on src/features/youtube/components/YoutubePlayer.vue
> +      @include css_anim($item: all, $time: .2s, $style: cubic-bezier(0, 0, 0.2, 1));
точно all нужно? лишняя работа для браузера, может стоит указать те свойства, которые действительно проходят transition?

2023-07-05 13:38 UTC, TroAlexis commented on src/features/youtube/composition/useYoutube.ts
> +      });
в ютуб сервис может такие запросы выделить?

2023-07-05 13:38 UTC, TroAlexis commented on src/features/youtube/views/YoutubeView.vue
> +                Дата добавления: {{ getDate(video.created) }}
может функцию назовём "getFormattedDate", чтобы отразить суть лучше? она ведь возвращает отформатированную строку? или 'getNumericDate', если там 01.12.23. условно

2023-07-05 13:39 UTC, TroAlexis commented on src/common/services/HTTPService.ts
> +  );
хотя выглядит как просто хелпер

2023-07-06 20:42 UTC, svifty7 commented on src/common/services/HTTPService.ts
> +  );
вынес в хелпер, а за одним и `getBaseURL`

2023-07-06 20:43 UTC, svifty7 commented on src/components/UI/kit/UiSwitch.vue
> +      </span>
убрал

2023-07-06 20:43 UTC, svifty7 commented on src/features/youtube/components/YoutubeAddVideo.vue
> +  const rules = reactive({
убрал

2023-07-06 20:44 UTC, svifty7 commented on src/features/youtube/components/YoutubeEditVideo.vue
> +  };
перечитал доку по аксиосу - можно вообще не проверять, он пропускает все статусы 2хх, на остальные ошибку выдает

2023-07-06 20:45 UTC, svifty7 commented on src/features/youtube/components/YoutubePlayer.vue
>        h(
это был копипаст) переделал

2023-07-06 20:45 UTC, svifty7 commented on src/features/youtube/components/YoutubePlayer.vue
> +      @include css_anim($item: all, $time: .2s, $style: cubic-bezier(0, 0, 0.2, 1));
пофиксил

2023-07-06 20:46 UTC, svifty7 commented on src/features/youtube/composition/useYoutube.ts
> +      });
да, вынес) было лень уже просто)

2023-07-06 20:47 UTC, svifty7 commented on src/features/youtube/views/YoutubeView.vue
> +                Дата добавления: {{ getDate(video.created) }}
сделал даже чуть лучше, чтобы вызывать сразу функцию и в нее можно было формат передавать, а не композицию вытаскивать, может быть стоит в хелпер вынести это вместо композиции

2023-07-07 10:47 UTC, TroAlexis approved these changes

2023-07-07 10:49 UTC, merged