188-UIKit/Search
TTG-Club/ttg-club-frontend pull request #197
Opened 2023-10-14 20:11 UTC by olegvolkov91

Реализация #1 UiSearch из UiKit 
[Issue 196 ](https://github.com/TTG-Club/ttg-club-frontend/issues/196)

[Темная тема](https://drive.google.com/file/d/1BBVeoqQQ_gLBpMkuCWS4zdvUx1eDSpIi/view?usp=sharing)
[Светлая тема](https://drive.google.com/file/d/1BiUOXnCZfmR9XO6atpHQ5ts99EqB2Niz/view?usp=sharing)

2023-10-16 08:17 UTC, svifty7 requested changes

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +          @include media-min($md) {
отступ забыл)

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +      @include media-min($lg) {
отступ забыл)

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +  }
лучше сделать нативными `:focus/:focus-within` и `:hover`

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +  }
лучше сделать нативным `:disabled` и у меня под сомнением что-то насчет прозрачности, т.к. будет виден интерфейс под поиском, если он вдруг там окажется

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +  }
плюс, если поле `disabled`, то иконки, которые имеют события, тоже сделать недоступными для взаимодействия

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +      </span>
это, скорее всего лучше на `<button/>` переделать, а еще лучше на `<ui-button/>`

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +      modelValue: '',
вот эту штуку сейчас можно через `defineModel` объявлять

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +  const { focused: inputFocus } = useFocus(input, { initialValue: false });
можно добавить пропс `initialFocus` и добавить в `initialValue`, чтобы можно было управлять этим из внешних компонентов

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +  const { disabled, placeholder } = props;
не уверен, но такой подход может реактивность сломать
пока что лучше использовать `const {disabled, placeholder} = toRefs(props)`

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +      placeholder: 'Placeholder'
стоит задать русское значение по умолчанию, например, `Поиск...`, как в фильтре или на странице поиска

2023-10-16 08:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +  const inputValue = useVModel(props, 'modelValue', emit);
при `defineModel` это уже не потребуется

2023-10-16 09:33 UTC, olegvolkov91 commented on src/assets/styles/variables/colors.scss
> +  'border-hover': #404040,
здесь я просто переиспользовал цвет из переменной --text-color который указан в figma, чтобы не добавлять в стилях вот так 

border-color: var(--text-color);

2023-10-16 22:17 UTC, svifty7 requested changes

2023-10-16 22:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +        :class="[$style.icon]"
раз используем `button`, то лучше и класс как `.button` сделать))

2023-10-16 22:17 UTC, svifty7 commented on src/shared/ui/kit/UiSearch.vue
> +    }
отступы между элементами не забывай везде)

2023-10-17 09:04 UTC, olegvolkov91 commented on src/shared/ui/kit/UiSearch.vue
> +  }
если убрать .ui-search.hovered и сделать таким образом .hovered, то из-за веса стили не применяются,  только через !important , а это моветон.

2023-10-18 15:58 UTC, svifty7 approved these changes

2023-10-18 15:58 UTC, merged