[TTG-3] Создать Токенатор
TTG-Club/ttg-club-frontend pull request #217
Opened 2023-10-27 19:49 UTC by olegvolkov91

2023-10-27 19:52 UTC, olegvolkov91 commented on src/features/menu/NavMenu.vue
> +  const showedNavItems = computed(() => {
Это было добавлено, в целях тестирования, так как на бэке это еще не реализовано

2023-10-28 17:48 UTC, svifty7 commented on src/assets/icons/svg/zoom/zoom-out.svg
папка `zoom` уже будет присутствовать в названии иконки, сами файлы нужно подписать вот так: `in`/`out`

2023-10-28 17:48 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +          console.log('ЧТО-ТО ПОШЛО НЕ ТАК', err);
вместо `console.log` - `useToast`)

2023-10-28 17:48 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +        const selectedFile = source[0] as File;
лучше стараться избегать Type Assertion, в будущем могут появиться проблемы с неаккуратным использованием

2023-10-28 17:48 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +            });
это вроде можно вынести в метод отдельный и использовать тут и в `onMounted`

2023-10-28 17:48 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenView.vue
> +      background: url('./assets/bg.png') no-repeat;
предлагаю сделать через `vue-lazyload`

2023-10-28 17:48 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenView.vue
> +      background: url('./assets/bg.png') no-repeat;
и вынести это в `/public/img/dark`, т.к. картинка будет меняться в зависимости от темы

2023-10-28 17:48 UTC, svifty7 commented on src/shared/ui/CustomSlider.vue
> +  <div :class="[$style['custom-slider'], $style.default]">
`div` можно вполне переделать в `label`))

2023-10-28 17:48 UTC, svifty7 commented on src/shared/ui/CustomSlider.vue
> +  }
тут работает `scss`, так что можно сделать обычные наследование классов через `&`

2023-10-28 20:47 UTC, olegvolkov91 commented on src/shared/ui/CustomSlider.vue
> +  <div :class="[$style['custom-slider'], $style.default]">
что-то с label у меня не клеится, можешь попробовать если хочешь )

2023-10-28 21:11 UTC, amstiel commented on public/img/dark/bg-token.png
Многовато картинки весят. Может попробуем их пожать/перевести в webp?

Например, с помощью этого https://squoosh.app/

2023-10-28 21:15 UTC, olegvolkov91 commented on public/img/dark/bg-token.png
ты за bg-token.png ? Это к @peterkogit , можно ли их сделать webp

2023-10-29 10:17 UTC, olegvolkov91 commented on public/img/dark/bg-token.png
апдейтнули в web

2023-10-30 19:17 UTC, svifty7 requested changes

2023-10-30 19:17 UTC, svifty7 commented on src/assets/styles/theme.scss
> +    --bg-token: url('/img/#{if($is-name-success, "#{$theme-name}", "dark")}/bg-token.webp');
че-т пока под сомнением стоит ли это в переменную вытаскивать сюда, может лучше в компонент перетащить?

2023-10-30 19:17 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +        <image :xlink:href="getImageSource(backgroundImage)" />
получится ли это в `computed` вытащить?

2023-10-30 19:17 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +        :xlink:href="getImageSource(borderImage)"
аналогично

2023-10-30 19:17 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +          @mousemove.prevent.capture="dragElement"
можно вот это использовать, чтоб свою логику не использовать https://vueuse.org/core/useDraggable/

2023-10-30 19:17 UTC, svifty7 commented on src/pages/Tools/Tokenator/TokenView.vue
> +    const svgNode = document.getElementById('downloadable-token-svg');
через `ref` лучше сделать

2023-10-30 19:17 UTC, svifty7 commented on src/shared/ui/kit/slider/UiRangeSlider.vue
> +  });
пропсы лучше через интерфейс сделать `withDefaults(defineProps<{}>(), {})`

2023-10-30 19:17 UTC, svifty7 commented on src/shared/ui/kit/slider/UiRangeSlider.vue
> +  const emit = defineEmits(['update:minValue', 'update:maxValue']);
тоже через типы сделать `defineEmits<{(e: 'name:of-emit', v: TypeOfReturningValue): void}>()`

2023-10-30 19:17 UTC, svifty7 commented on src/shared/ui/kit/slider/UiRangeSlider.vue
> +    slider.value?.style.setProperty('--progressRight', `${right}%`);
это можно в `ref` сделать, а в стилях использовать `v-bind(refVarName)`

2023-10-30 21:06 UTC, olegvolkov91 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +          @mousemove.prevent.capture="dragElement"
я попробовал, оно не хочет ехать нормально, если будет желание, можешь потом отрефакторить, я посмотрю на код

2023-10-30 21:07 UTC, olegvolkov91 commented on src/assets/styles/theme.scss
> +    --bg-token: url('/img/#{if($is-name-success, "#{$theme-name}", "dark")}/bg-token.webp');
почему? как это делать в компоненте?

2023-10-30 21:09 UTC, olegvolkov91 commented on src/pages/Tools/Tokenator/TokenStamp.vue
> +        :xlink:href="getImageSource(borderImage)"
а какой смысл? ты же в чате предложил его с бекенда тянуть, тоже и бекграунда касается. Этот кусок просто будет удален

2023-10-30 21:10 UTC, olegvolkov91 commented on src/pages/Tools/Tokenator/TokenView.vue
> +    const svgNode = document.getElementById('downloadable-token-svg');
а можно пример?

2023-10-31 08:58 UTC, olegvolkov91 commented on src/shared/ui/kit/slider/UiRangeSlider.vue
> +    slider.value?.style.setProperty('--progressRight', `${right}%`);
пример в студию, пжлста

2023-11-02 21:52 UTC, merged