feat: implement Chip component
TTG-Club/ttg-club-frontend pull request #221
Opened 2023-10-28 21:12 UTC by amstiel

2023-10-30 19:05 UTC, svifty7 requested changes

2023-10-30 19:05 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.d.ts
> +export type TChipSize = 'l' | 'm' | 's' | 'xs';
предлагаю такие обозначения: `lg`, `md`, `sm` - без `xs`,  т.к. такого размера на сайте нигде нет, либо добавлять это везде
привести к виду как в `UiButton`)

2023-10-30 19:05 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.vue
> +      v-if="$slots.icon && count === undefined"
не понял зачем тут `count === undefined`, т.к. иконка может быть и со счетчиком)
плюс надо добавить дефолтную иконку с крестиком показывающуюся по пропсу `removable` и при клике эмитить `remove`

2023-10-30 19:05 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.vue
> +    &-s {
все размеры привести к такому же формату как в пропсе исходя из коммента

2023-11-01 18:10 UTC, amstiel commented on src/shared/ui/kit/chip/UiChip.d.ts
> +export type TChipSize = 'l' | 'm' | 's' | 'xs';
Собственно, в макете было 4 размера. Именно их и сделал. Могу аббревиатуры обновить, конечно. Но 4 размера оставить.

2023-11-01 18:11 UTC, amstiel commented on src/shared/ui/kit/chip/UiChip.vue
> +      v-if="$slots.icon && count === undefined"
> т.к. иконка может быть и со счетчиком

В макете явно сказано, что __нельзя__ :)

А про дефолтную иконку закрытия - хорошая мысль, можно.

2023-11-01 18:11 UTC, amstiel commented on src/shared/ui/kit/chip/UiChip.vue
> +    &-s {
См. выше

2023-11-01 18:37 UTC, amstiel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Chips](https://trello.com/c/hRbT9iLv/1-chips)

2023-11-03 16:30 UTC, svifty7 requested changes

2023-11-03 16:30 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.vue
> +      v-if="$slots.icon && count === undefined"
Резюмирую дискорд: отображается `Текст + крестик/иконка` или `Текст + счетчик`, поэтому при наведении на чипс можно заменять иконку на крестик, если стоит `closable: true`
1. вместо слота под иконку используем `<svg-icon />` и пропс `icon`
2. добавляем дефолтный крестик отображаемый только при `closable`, он будет эмитить `close` на `@click.left.exact.prevent.stop=""`
3. вместо `count !==/=== undefined` можно использовать `count` / `!count`, не думаю, что надо отображать счетчик, если там 0 будет)

2023-11-03 16:30 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.vue
> +    modelValue: true
у всех `required: false` должны быть значения по умолчанию

2023-11-03 16:30 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.vue
> +  .chip {
предусмотреть отступы между чипсами через `& + &`, должно сработать

2023-11-03 16:30 UTC, svifty7 commented on src/shared/ui/kit/chip/UiChip.vue
> +    clickable: true,
думаю, можно убрать этот пропс вообще

2026-06-26 08:20 UTC, closed without merging