История бросков
TTG-Club/ttg-club-frontend pull request #254
Opened 2024-02-28 09:40 UTC by raidorev

Что было сделано:
- Общее хранилище для бросков - `RollStore`. Именно там хранится список всех бросков (для хранения используется `localStorage`, максимум элементов - 100). Есть две мутации - `addRoll` и `registerRoll`. `addRoll` просто добавляет в список, `registerRoll` добавляет в список и отправляет новый бросок в другие "источники" (пока это broadcast channel и eventBus). Информация об `eventBus` ниже.
- **Добавлена новая зависимость** - [mitt](https://github.com/developit/mitt). С помощью нее реализован `eventBus`. Пока там только одно событие - `Roll.New`. Сделано это для того, чтобы иметь возможность не зависеть от какой-то фичи в другой фиче. Да и для удобства реализации некоторого функционала (когда есть source и targets, к примеру). В перспективе можно будет использовать для реализации отправки бросков в сторонние сервисы (дискорд) и не громоздить это все в `RollStore`. Посчитал, что тут это будет очень удобно. Сам пакет `mitt` весит 200 байт, так что на перформанс это особо не повлияет. 
- Переработан composable `useDiceRoller`. Теперь там происходит только регистрация броска в `RollStore`. Рендеринг бросков вынес в `RollRenderer` (`shared/utils/roll.ts`).
- Добавлена новая фича - `dice-notification`. Она занимается показом тостов с бросками при событии `Roll.New`. В `App.vue` она включается.
- Добавлена новая фича - `dice-history`. Собственно, самое главное.
  - Стили я писал не через `module`, а через `scoped`. Я просто привык писать через БЭМ и модули для этого не очень удобные. 
  - Рендерится главные компонент в `App.vue` (мне это не очень нравится, но не стал сильно заморачиваться с архитектурой в этом моменте). 
  - Можно менять высоту, нажимая и перемещая верхнюю границу окна. Высота окна сохранятся в `localStorage`. Я постарался сделать так, чтобы окно никогда не выходило за пределы viewport, но мб я что-то упустил.
  - Бросок по формуле
    - Поле ввода принимает любую валидную формулу. Источник броска в данном случае будет "Бросок по формуле". При вводе невалидной формулы значок к6 (справа) подсвечивается красным цветом на секунду.
    - Реализовано простая навигация по истории бросков. Если нажать стрелочку вверх, то в поле ввода подставится предыдущая формула. Если нажать еще раз, на одну раньше. И так далее. При нажатии стрелочки вниз идем по истории вперед. **История формул не сохраняется в `localStorage`**.
- Добавлена новый вид кнопки в UIKit - `UiFab`. Это минимальная реализация FAB, без ненужных моментов.

2024-02-28 09:44 UTC, raidorev commented
Есть один момент, который мне очень не нравится - реализация источника броска. Сейчас я просто прошелся по всем страницам и добавил там `entityName` в компонент `ContentDetail`. Вообще очень часто повторяется логика запроса данных в страницах. По-хорошему это надо куда-то вынести.

2024-02-28 09:44 UTC, raidorev commented
Еще надо бы добавить `title` в `dice-roller` на бэке (наверное, не до конца разобрался). Т.е. сейчас бросок атаки и урона выглядит так: 
![image](https://github.com/TTG-Club/ttg-club-frontend/assets/34508963/e471b836-725d-4e13-ac6f-7ed0db67e9dc)
Нужно бы сделать не "Бросок", а "Атака" и "Урон" соответственно.

2024-02-28 13:58 UTC, svifty7 requested changes

2024-02-28 13:58 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistoryWindowContent.vue
> +      border-bottom: 1px solid rgb(255 255 255 / 8%);
под цвет используется `var(--border)`

2024-02-28 13:58 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistoryWindowContent.vue
> +      border-bottom: 1px solid rgb(255 255 255 / 8%);
под цвет используется `var(--border)`

2024-02-28 13:58 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistoryWindowContent.vue
> +      border-bottom: 1px solid rgb(255 255 255 / 8%);
и думаю рамку правильнее добавить на инпут, т.к., если инпут мы по какой-то причине скроем (контентную часть мы точно не скроем, т.к. она и есть фича), то останется рамка не нужна

2024-02-28 13:58 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistoryWindowContent.vue
> +      }
эти стили у нас основном файле стилей + есть вероятность что такой способ записи скоро не будет работать (хром уже убрал поддержку)

2024-02-28 13:58 UTC, svifty7 commented on src/shared/stores/RollStore.ts
> +      eventBus.emit('Roll.New', { entry: roll, toastOptions });
ключи стоит вынести в enum

2024-02-28 13:58 UTC, svifty7 commented on src/shared/ui/kit/button/UiFab.vue
> +        .map((p) => [$style[`ui-fab--position-${p}`], true]),
чтоб не городить в модулях такие длинные класса можно упростить так — `$style[position]` и в остальных местах так же

2024-02-28 13:58 UTC, svifty7 commented on src/shared/ui/kit/button/UiFab.vue
> +    }
а здесь использовать `&.top-left`

2024-02-28 13:58 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistoryInput.vue
> +  const history: string[] = [];
а вот такая история не подойдет сюда? https://vueuse.org/core/useRefHistory/

2024-02-28 13:58 UTC, svifty7 commented on src/shared/stores/RollStore.ts
> +  const rolls = useLocalStorage<RollEntry[]>('rolls', []);
тут все еще убежден, что нам следует использовать `SessionStorage`:
1. зачем человеку хранить броски дольше одной сессии? 
2. если это крайней необходимая фича в каких-то ситуациях, то лучше сделать галочку и по ней переключать `SessionStorage` -> `LocalStorage`
3. `LocalStorage` в итоге сможем забить, если пользователь активно и долго пользуется этой фичей

2024-02-28 13:58 UTC, svifty7 commented on src/shared/stores/RollStore.ts
> +  const notificationMode = useLocalStorage(
для сохранения такой настройки можно использовать IndexedDB, чтобы LocalStorage не забивался тысячами непонятных ключей, с которыми потом сложно будет ориентироваться
плюс, возможно, некоторые настройки еще добавятся
```js
const store = localforage.createInstance({
  name: DB_NAME,
  storeName: 'dice_roller',
});
```

2024-02-28 13:58 UTC, svifty7 commented on src/shared/ui/BottomRightWindow.vue
> +  const height = useLocalStorage('bottom-right-window-height', MIN_HEIGHT);
это тоже в IndexedDB можно вынести

2024-02-28 13:58 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistoryItem.vue
> +    $root: &;
лишняя переменная

2024-02-28 13:58 UTC, svifty7 commented on src/assets/styles/modules/navbar.scss
> +    min-width: var(--navbar-width);
что-то у меня есть ощущение, что это может повлиять на те места, где задается ширина контента)) проверь, пожалуйста, по крайней мере там, где есть переменная `--max-content`

2024-02-28 13:58 UTC, svifty7 commented on package.json
> +    "mitt": "^3.0.1",
у нас уже есть `vueuse`, может стоит использовать его `eventBus`?) https://vueuse.org/core/useEventBus/

2024-02-28 13:58 UTC, svifty7 commented on package.json
> +    "mitt": "^3.0.1",
у нас уже есть `vueuse`, может стоит использовать его `eventBus`?) https://vueuse.org/core/useEventBus/

2024-02-28 14:24 UTC, raidorev commented on package.json
> +    "mitt": "^3.0.1",
Изначально так и хотел, но он там неудобный и на одно событие.

2024-02-28 14:27 UTC, raidorev commented on src/features/dice-history/ui/DiceHistory.vue
> +    @click="toggle()"
Я бы не стал опускать скобки, это эквивалент `() => { toggle() }`, что выглядит корректнее, чем передавать в функцию аргумент, даже если его нет с сигнатуре.

2024-02-28 14:33 UTC, raidorev commented on src/shared/stores/RollStore.ts
> +      eventBus.emit('Roll.New', { entry: roll, toastOptions });
Там работает autocomplete т.к. все эти события описаны в типе `Events`. Да и если вписать несуществующее событие, то будет type error. В целом то можно, но тогда теряется смысл разделения событий по скоупу. Т.е. сейчас скоуп - `Roll.*`. Можно скоуп делать многословным и многоуровневым (`SomeScope.SubScope.Event`).

2024-02-28 14:35 UTC, raidorev commented on src/shared/ui/kit/button/UiFab.vue
> +        .map((p) => [$style[`ui-fab--position-${p}`], true]),
Я просто не могу писать не по БЭМу, сорри. Тут или переписать на scoped, или уже отказаться от БЭМа.

2024-02-28 14:54 UTC, raidorev commented on src/features/dice-history/ui/DiceHistoryWindowContent.vue
> +      }
Ну эта запись для обратной совместимости, выше современный способ. А в базовых стилях вроде ширина 14px (хотя эта ширина в новых браузерах и не может быть задана в пикселях).
Если убрать стилизацию скроллбара, то не будет соответствовать макету: 
![image](https://github.com/TTG-Club/ttg-club-frontend/assets/34508963/81008592-f89e-4d8c-a0c4-1d7da2076eee)

2024-02-28 15:15 UTC, raidorev commented on src/features/dice-history/ui/DiceHistoryInput.vue
> +  const history: string[] = [];
Особых преимуществ не увидел, зачем использовать какое-то API и реактивность, когда нужен просто массив строк по сути.

2024-02-28 15:35 UTC, svifty7 commented on src/shared/stores/RollStore.ts
> +      eventBus.emit('Roll.New', { entry: roll, toastOptions });
автокомплит, конечно, хорошо, но это может не работать в некоторых IDE и в целом может превратиться в кашу в будущем) а так мы можем контролировать нейминги и заранее посмотреть возможные варианты)

2024-02-28 15:38 UTC, svifty7 commented on src/shared/stores/RollStore.ts
> +  const rolls = useLocalStorage<RollEntry[]>('rolls', []);
в дискорде пришли к тому, чтобы использовать `localforage`

2024-04-18 09:12 UTC, Magistrus commented
> Нужно бы сделать не "Бросок", а "Атака" и "Урон" соответственно.

Это в процесс и да это на бэке

2024-04-18 10:26 UTC, Magistrus approved these changes

2024-04-18 22:08 UTC, svifty7 commented on src/features/dice-history/ui/DiceHistory.vue
> +    @click="toggle()"
все же я склонен к варианту, который по дефолту во eslint vue https://eslint.vuejs.org/rules/v-on-handler-style.html#method-inline-function-default
 
```js
// по факту, мы можем даже в нативном js использовать без скобок
function toggleOn() {
    console.log('Toggled ON');
}

setTimeout(toggle);
```

```js
// или когда присваиваем элементу действие на событие "клик" 
function toggleOn() {
    console.log('Toggled ON');
}

$0.onclick = toggleOn
```

2024-04-19 08:08 UTC, raidorev commented on src/features/dice-history/ui/DiceHistory.vue
> +    @click="toggle()"
Может тогда добавим правило для еслинта для этого?

2024-04-23 07:11 UTC, merged