feat: redirect from `traits` to `feats`
TTG-Club/ttg-club-frontend pull request #260
Opened 2024-03-12 17:31 UTC by svifty7

2024-03-13 08:20 UTC, raidorev commented
А разве не было обсуждения, что отказываемся от `.d.ts` файлов?

2024-03-13 08:28 UTC, raidorev requested changes

2024-03-13 08:28 UTC, raidorev commented on src/pages/character/feats/feats-detail/FeatDetail.vue
> +      abortController.value = new AbortController();
Может, это вынести из try/catch блока, ошибка же не может возникнуть. Чтобы блоки try/catch были как можно меньше

2024-03-13 08:28 UTC, raidorev commented on src/pages/character/feats/feats-detail/FeatDetail.vue
> +  onBeforeRouteUpdate(async (to, from, next) => {
```suggestion
  onBeforeRouteUpdate(async (to) => {
```
Вроде лишние параметры

2024-03-13 08:28 UTC, raidorev commented on src/pages/index.ts
> +  TraitsPage, // TODO: remove
Если TODO останется после мержа, стоит добавить пояснение, ссылку на этот ПР или обсуждение. А то потом непонятно будет.

2024-03-13 08:28 UTC, raidorev commented on src/shared/types/character/Feats.d.ts
> +export enum FeatsFilterDefaults {
А почему enum а не константа? Не похоже не enum в моем понимании.

2024-03-13 08:28 UTC, raidorev commented on src/shared/types/character/Feats.d.ts
Разве не обсуждали, что хотим избавляться от `.d.ts` файлов?

2024-03-13 08:28 UTC, raidorev commented on src/shared/ui/DetailTooltip.vue
Такое же предложение про TODO

2024-03-21 14:06 UTC, svifty7 commented on src/shared/types/character/Feats.d.ts
да, в отдельном МРе сделаем

2024-03-21 14:07 UTC, svifty7 commented on src/shared/types/character/Feats.d.ts
> +export enum FeatsFilterDefaults {
тоже переделаем в МРе по переименованию `.d.ts`

2024-03-22 09:00 UTC, raidorev requested changes

2024-03-22 09:00 UTC, raidorev commented on src/pages/character/feats/feats-detail/FeatDetail.vue
> +  const abortController = ref<AbortController>();
А зачем тут используется ref? Вроде реактивность не нужна

2024-03-22 17:56 UTC, raidorev approved these changes

2024-03-22 18:59 UTC, merged