Обновление отображение классов в заклинаниях и удаление цены в сокровищнице
TTG-Club/ttg-club-frontend pull request #53
Opened 2023-03-16 17:24 UTC by peterkogit

2023-03-17 07:05 UTC, svifty7 requested changes

2023-03-17 07:05 UTC, svifty7 commented on src/views/Character/Spells/SpellBody.vue
> +                        <span v-if="key !== spell.classes.length - 1">,&nbsp;</span>
неразрывный пробел на мобилке может сломать отображение - лучше просто пробел использовать

2023-03-17 07:05 UTC, svifty7 commented on src/views/Character/Spells/SpellBody.vue
> +            DetailTopBar
импорт на 155 строке теперь лишний

2023-03-17 07:05 UTC, svifty7 commented on src/views/Inventory/MagicItems/MagicItemLink.vue
> -                        </div>
а у торговца или где-то еще это не используется?

2023-03-17 10:42 UTC, peterkogit commented on src/views/Inventory/MagicItems/MagicItemLink.vue
> -                        </div>
> а у торговца или где-то еще это не используется?

Вроде как может быть, тогда тебе надо поправить что бы у торговца не было "Настройки"

2023-03-27 19:46 UTC, svifty7 approved these changes

2023-03-27 19:46 UTC, merged