feature: lists virtualisation
TTG-Club/ttg-club-frontend pull request #65
Opened 2023-04-15 07:58 UTC by TroAlexis

- Добавил базовый компонент виртуального списка
- Добавил компонент списка с группировкой
- Виртуализация в - магических предметах, чертах, предысториях. Также список с виртуализацией и группировкой в заклинаниях

Дополнительно:
- Поправил правила в eslint конфиге для работы с script setup
- Добавил крошечную библиотеку [clsx](https://www.npmjs.com/package/clsx) для удобного формирования списка классов (в итоге не пригодилась в текущем ПР, но понадобится в дальнейшем).

2023-04-17 10:32 UTC, svifty7 commented
Появился баг, что правый столбец не раскрывается на всю ширину страницы
<img width="635" alt="image" src="https://user-images.githubusercontent.com/45195424/232459673-762ff5a9-8aa9-4ea9-996a-bc030de04fe4.png">

2023-04-17 11:07 UTC, svifty7 requested changes

2023-04-17 11:07 UTC, svifty7 commented on src/types/Shared/Lodash.types.ts
> +import type { LoDashStatic } from 'lodash';
Не получится отсюда импортировать только нужный тип? При деструктуризации импорта библиотеки она импортируется полностью, чем увеличивает размер модуля при сборке

2023-04-17 11:07 UTC, svifty7 commented on src/components/list/GroupedList/GroupedList.vue
> +<script setup lang="ts">
Думаю, что стоит назвать компонент примерно так - VirtualGroupedList, т.к. это виртуальный группированный список, а не просто группировка

2023-04-17 11:07 UTC, svifty7 commented on src/views/Character/Spells/SpellsView.vue
> +                url: `${ level }`,
Почему в поле `url` записывается уровень заклинания?

2023-04-17 11:10 UTC, TroAlexis commented on src/types/Shared/Lodash.types.ts
> +import type { LoDashStatic } from 'lodash';
Неа, он не эскпортируется, к сожалению. Здесь же тип импортируется, это не должно никак повлиять на размер модуля, но я проверю и отпишусь наверняка.

2023-04-17 11:12 UTC, TroAlexis commented on src/views/Character/Spells/SpellsView.vue
> +                url: `${ level }`,
ну почему-то у элементов нет идентификатора никакого, кроме как url (и он используется как ключ в данном случае), поэтому и в группе такой же должен быть 🤷

2023-04-22 10:23 UTC, svifty7 requested changes

2023-04-22 10:23 UTC, svifty7 commented on src/common/const/index.ts
> +export const BREAKPOINTS: Breakpoints<TBreakpoint> = {
а получится это из `scss` экспортнуть? я как-то такое делал на работе)

2023-04-22 10:23 UTC, svifty7 commented on src/components/list/ListRow.vue
> +        '--list-row-columns': props.columns
если это не используется нигде во вложенных компонентах, то можно через v-bind сделать лучше)

2023-04-22 10:23 UTC, svifty7 commented on src/components/list/ListRow.vue
> +        '--list-row-columns': props.columns
https://vuejs.org/api/sfc-css-features.html#v-bind-in-css - как в доке

2023-04-22 10:25 UTC, TroAlexis commented on src/common/const/index.ts
> +export const BREAKPOINTS: Breakpoints<TBreakpoint> = {
да, можно сделать, делал тоже пару раз, но я помню голову парил слишком долго, чтобы нормально заработало) попробую запилить 👌

2023-04-22 10:26 UTC, TroAlexis commented on src/components/list/ListRow.vue
> +        '--list-row-columns': props.columns
согласен, давай так
я и забыл про эту штуку, тоже как-то использовал, когда проект делал на vue3

2023-04-22 11:01 UTC, svifty7 commented on src/common/const/index.ts
> +export const BREAKPOINTS: Breakpoints<TBreakpoint> = {
да, тоже помню, что как-то не очень работало, поэтому не в приоритете)) медиа-запросы очень редко меняться будут, а может и вовсе не будут)))

2023-05-10 12:55 UTC, svifty7 approved these changes

2023-05-11 06:22 UTC, merged