тестовые таски от маслёнка
TTG-Club/ttg-club-frontend pull request #66
Opened 2023-04-18 22:53 UTC by UrSenpaiii

2023-04-19 13:23 UTC, UrSenpaiii commented on src/components/UI/modals/SearchModal.vue
> +                            :maxlength="255"
Это не решение, это рудимент.
Изначально прокидывал туда переменную, потом просто забыл убрать двоеточие

2023-04-20 12:03 UTC, svifty7 requested changes

2023-04-20 12:17 UTC, UrSenpaiii commented on src/components/UI/modals/SearchModal.vue
> +            padding: 0 2px;
Хорошо. Я вообще думал не лезть туда, но всё же полез. падинг добавил, потому что верстал под то, что есть в продакшене сейчас

2023-04-22 10:30 UTC, svifty7 approved these changes

2023-04-22 10:52 UTC, merged