Fix/UI input validation
TTG-Club/ttg-club-frontend pull request #77
Opened 2023-04-30 12:59 UTC by UrSenpaiii

Fixes TTG-Club/github-private#208

2023-04-30 18:38 UTC, svifty7 requested changes

2023-04-30 18:38 UTC, svifty7 commented on src/components/UI/kit/UiEraseButton.vue
> +<script>
думаю стоит сделать вот так - `<script setup lang="ts">`, а дальше уже экспорт и defineComponent не нужен)

2023-04-30 18:38 UTC, svifty7 commented on src/components/UI/kit/UiEraseButton.vue
> +.filter__search_clear {
в стилях не хватает отступа 4 пробела)

2023-04-30 18:38 UTC, svifty7 commented on src/components/UI/kit/UiInput.vue
> +            maxInputLength: {
мне кажется, излишне будет новое название, старое вполне себе хорошо объясняло назначение

2023-04-30 18:38 UTC, svifty7 commented on src/components/UI/kit/UiInput.vue
> +            typeValidate(e) {
не совсем понял что за метод появился, расскажешь потом что оно дает?)

2023-04-30 18:38 UTC, svifty7 commented on src/components/filter/ListFilter.vue
> +                <ui-erase-button
не совсем уверен, что необходим компонент... но посмотрим позже)

2023-04-30 18:38 UTC, svifty7 commented on src/components/filter/ListFilter.vue
> +        border: 0;
радиусы не забыл?)

2023-04-30 18:38 UTC, svifty7 commented on src/views/Tools/MadnessView.vue
> +                                is-number
надо будет переделать на параметр `type="number"` и подобные, мне кажется, лучше будет и в скриптах, соответственно, подправить

2023-04-30 18:38 UTC, svifty7 commented on src/views/Search/SearchView.vue
> +                                v-model.trim="search"
нужно в `$emit('update:model-value')` передавать уже с trim()

2023-04-30 19:02 UTC, TroAlexis requested changes

2023-04-30 19:11 UTC, UrSenpaiii commented on src/components/UI/kit/UiInput.vue
> +                }
гляну, как можно вынести. Просто при работе с keyCode не всегда помнишь какой код какой

2023-04-30 19:12 UTC, UrSenpaiii commented on src/components/filter/ListFilter.vue
> +                    @click="search = ''"
думаешь нужно? тогда везде, где этот компонент используется - нужно будет создавать этот метод

2023-05-01 07:51 UTC, UrSenpaiii commented on src/components/UI/kit/UiEraseButton.vue
> +<script>
Да я вот глянул, у вас вроде нигде или почти нигде setup нет

2023-05-01 07:54 UTC, UrSenpaiii commented on src/components/filter/ListFilter.vue
> +        border: 0;
а он там внутри основного блока поиска, не нужно

2023-05-01 17:18 UTC, UrSenpaiii commented on src/views/Tools/MadnessView.vue
>                                  placeholder="Количеств"
нет, там же в валидации props стоит Number, поэтому без этого он как минимум кидает варнинги всё время

2023-05-01 20:15 UTC, UrSenpaiii commented on src/components/UI/kit/UiInput.vue
> +            typeValidate(e) {
Для проверки введеных данных в инпут на основе props.type

2023-05-02 14:38 UTC, TroAlexis commented on src/components/UI/kit/UiEraseButton.vue
> +<script>
> Да я вот глянул, у вас вроде нигде или почти нигде setup нет

это мы недавно договорились с Никитой новые компоненты с script setup делать, на будущее)

2023-05-02 14:39 UTC, TroAlexis commented on src/views/Tools/MadnessView.vue
>                                  placeholder="Количеств"
не, это я про 'Количеств', не должно быть 'Количество'?

2023-05-02 14:40 UTC, TroAlexis commented on src/components/filter/ListFilter.vue
> +                    @click="search = ''"
ну это скорее для очистки шаблона от логики лишней

2023-05-02 14:42 UTC, TroAlexis commented on src/components/UI/kit/UiInput.vue
> +                    if (!isNum || (!isValueEmpty && !key)) {
а это точно теперь работает так же?
а то ты раньше проверял keyCode, а теперь заменилось на Number.isInteger 🤔

2023-05-02 21:41 UTC, UrSenpaiii commented on src/components/UI/kit/UiInput.vue
> +                    if (!isNum || (!isValueEmpty && !key)) {
да, всё работает, до этого были коды 1, 2, 3...0 клавиш, а сейчас там просто проверка на то, что это int. До этого я делал через keyCode потому что на каком то этапе написания этой проверки пришёл к ним из-за того, что нельзя превентить кнопки стрелочек и тп, вот и отслеживал по keyCodes

2023-05-02 21:43 UTC, UrSenpaiii commented on src/components/UI/kit/UiEraseButton.vue
> +<script>
> новые компоненты с script setup
Т.е. если я буду их потихоньку на setup переносить, то ок?

2023-05-04 09:46 UTC, TroAlexis commented on src/components/UI/kit/UiEraseButton.vue
> +<script>
> > новые компоненты с script setup
> 
> Т.е. если я буду их потихоньку на setup переносить, то ок?

да, будет супер

2023-05-04 09:46 UTC, TroAlexis commented on src/components/UI/kit/UiInput.vue
> +                    if (!isNum || (!isValueEmpty && !key)) {
> да, всё работает, до этого были коды 1, 2, 3...0 клавиш, а сейчас там просто проверка на то, что это int. До этого я делал через keyCode потому что на каком то этапе написания этой проверки пришёл к ним из-за того, что нельзя превентить кнопки стрелочек и тп, вот и отслеживал по keyCodes

ок, супер

2023-05-10 12:41 UTC, svifty7 requested changes

2023-05-10 12:41 UTC, svifty7 commented on src/views/Search/SearchView.vue
> +                            <ui-erase-button
давай, плиз, еще сделаем кнопку стирания прямо в компоненте `ui-input` с параметром `clearable`
т.е. чтобы крестик появлялся, когда в инпуте есть текст и `clearable="true"`

2023-05-10 12:43 UTC, svifty7 requested changes

2023-05-10 12:43 UTC, svifty7 commented on src/views/Search/SearchView.vue
> +                            <ui-erase-button
давай, плиз, еще сделаем кнопку стирания прямо в компоненте ui-input с параметром clearable т.е. чтобы крестик появлялся, когда в инпуте есть текст и clearable="true"

2023-05-14 07:30 UTC, UrSenpaiii commented on src/views/Search/SearchView.vue
> +                            <ui-erase-button
@TTG-Club/frontend Люди добрые, ревью закройте :)

2023-05-16 21:55 UTC, closed without merging