Fix/button
TTG-Club/ttg-club-frontend pull request #82
Opened 2023-05-13 15:44 UTC by peterkogit

Update button

2023-05-13 17:08 UTC, UrSenpaiii approved these changes

2023-05-13 20:37 UTC, svifty7 requested changes

2023-05-13 20:37 UTC, svifty7 commented on src/components/UI/DetailTopBar.vue
> +    .base-modal__body {
здесь такого элемента нет вообще, так что лучше будет в `SpellBody.vue` на класс `.in-tooltip` сделать отступ. Либо как вариант на все `*Body.vue` детальники повесить класс `.detail-body` и глобально  на класс `.in-tooltip` сделать отступ

2023-05-13 20:37 UTC, svifty7 commented on src/components/UI/SectionHeader.vue
> +                class="section-header__control close"
у нас везде сейчас используется `.is-close`, `is-active`, `is-large` и т.д.

2023-05-13 20:37 UTC, svifty7 commented on src/components/UI/kit/UiButton.vue
> +            color: var(--text-color);border:1px solid var(--border);
перенос строки забыл

2023-05-13 20:37 UTC, svifty7 commented on src/components/UI/kit/UiButton.vue
> +        border: 1px solid var(--border);
а оно нужно?.. это же у всего и везде сейчас рамка появится и размер кнопок увеличится на 2px и местами интерфейс поедет

2023-05-13 20:37 UTC, svifty7 commented on src/components/UI/kit/UiButton.vue
> +            color: var(--text-color);border:1px solid var(--border);
зачем тут `border`, если он уже выше объявлен?

2023-05-13 20:37 UTC, svifty7 commented on src/components/UI/kit/UiButton.vue
> +                cursor: not-allowed;
это можно вынести в `.ui-butoon:disabled`, чтобы в каждом состоянии не копировать, т.к. вроде эта часть одинаковая везде

2023-05-14 05:49 UTC, peterkogit commented on src/components/UI/kit/UiButton.vue
> +        border: 1px solid var(--border);
Тут убрал

2023-05-14 05:49 UTC, peterkogit commented on src/components/UI/kit/UiButton.vue
> +            color: var(--text-color);border:1px solid var(--border);
Тут оставил

2023-05-14 05:50 UTC, peterkogit commented on src/components/UI/kit/UiButton.vue
> +                cursor: not-allowed;
Поправил там bg задаеться.

2023-05-14 05:50 UTC, peterkogit commented on src/components/UI/kit/UiButton.vue
> +            color: var(--text-color);border:1px solid var(--border);
Поправил

2023-05-14 06:09 UTC, peterkogit commented on src/components/UI/SectionHeader.vue
> +                class="section-header__control close"
Поправил

2023-05-14 06:20 UTC, svifty7 requested changes

2023-05-14 06:20 UTC, svifty7 commented on src/components/UI/kit/UiButton.vue
> +        // border: 1px solid var(--border);
гит хранит историю изменений, так что не нужен тут коммент

2023-05-14 06:20 UTC, svifty7 commented on src/components/UI/kit/UiButton.vue
> +            border:1px solid var(--border);
в итоге border все равно только в одной ситуации, нужно либо везде сделать его, либо сделать padding делать здесь меньше, чтобы размеры везде остались одинаковыми

2023-05-14 06:20 UTC, svifty7 commented on src/views/Character/Classes/ClassDetail.vue
> +                    background: var(--bg-main);
у нас там и так кнопки используются, почему бы не использовать их стандартный стиль ховера?

2023-05-14 06:20 UTC, svifty7 commented on src/views/Character/Classes/ClassDetail.vue
> +                border: 0;
прыгают кнопки теперь, смотрится так себе

2023-05-14 07:02 UTC, peterkogit commented on src/components/UI/kit/UiButton.vue
> +        // border: 1px solid var(--border);
Fix

2023-05-14 07:06 UTC, peterkogit commented on src/views/Character/Classes/ClassDetail.vue
> +                    background: var(--bg-main);
Там не кнопки, присмотрись

2023-05-18 15:21 UTC, closed without merging